spring.application.name=chandanv
spring.datasource.url=jdbc:mysql://localhost:3306/java_database?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.flyway.enabled=true
spring.flyway.locations=classpath:database/migrations
spring.flyway.baseline-on-migrate=true

jwt.secret = qwertyuiopasdfghjklzxcvbnm123456
jwt.expiration = 86400000